# Use Node 18 alpine image
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy the rest of the application
COPY . .

# Expose the port your app uses
EXPOSE 3000

# Command to run the app
CMD ["node", "app.js"]
